#logging
logging:
  level: DEBUG  # or DEBUG, WARNING, ERROR, CRITICAL
  log_dir: "logs"  # Log directory
  log_file: "data.log"  # Log file name

#numeric representation
max_base: 36
custom_digits : "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

#考虑限定数域，循环域
number_domain: [-1000,1000]

variable_atoms:
  - left_operand: "a"
  - right_operand: "b"

other_symbols_atoms:
  left_parenthesis: "(" 
  right_parenthesis: ")"
  equals_sign: "="
  nan_symbol: "NaN"  # 表示无解

#运算符生成
operator_symbol_min_len: 1
operator_symbol_max_len: 3
#对于条件
basic_operator_symbols: ["+", "-", "*", "/", "%"]
comparison_ops: ["==", ">", "<", ">=", "<=", "!="]
logical_connectors: ["and", "or"]
condition_numeric_range: 
  max_value: 1000
  min_value: 0 #不用负数，是因为其实一元符号里面有负数
condition_probabilities:
  1: 0.7
  2: 0.2
  3: 0.1
#对于分支数目
max_if_branches: 5

# 表达式生成
expr_variables: "a,b"
expr_numeric_range: 
  max_value: 1000
  min_value: 0 #不用负数，是因为其实一元符号里面有负数
expr_max_depth: 5  
expr_type_weights: 
  binary: 0.7
  unary_prefix: 0.2
  unary_postfix: 0
  atoms: 0.1
expr_atom_type_weights: #注意这里不同
  variable: 0.8
  number: 0.2

